-- =====================================================================
--  VENDU — Reclamos "la maquina no despacho" + gift cards  ·  ARCHIVO 10
--  Tablas del micrositio QR (schema `vendu`). El backend las usa cuando
--  se define DATABASE_URL (conexion directa `postgres`, BYPASSRLS).
--  Idempotente: se puede correr varias veces.
--  RLS activado para que la app (authenticated) solo pueda LEER.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS vendu;

CREATE TABLE IF NOT EXISTS vendu.giftcard_claims (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maquina_id  INTEGER      NOT NULL,
    mdb         TEXT         NOT NULL,
    producto    TEXT         NOT NULL,
    monto       NUMERIC(12,2),
    monto_real  NUMERIC(12,2),
    device_id   TEXT         NOT NULL,
    ip          TEXT,
    tx_key      TEXT UNIQUE,
    estado_cobro TEXT,              -- estado del cobro en cobros_maquina al emitir
    state       TEXT         NOT NULL DEFAULT 'PENDIENTE',
    gift_code   TEXT,
    mensaje     TEXT,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz
);

ALTER TABLE vendu.giftcard_claims ADD COLUMN IF NOT EXISTS estado_cobro TEXT;
-- productos reclamados (JSON: nombre, precio_bs, cantidad, producto_ids)
ALTER TABLE vendu.giftcard_claims ADD COLUMN IF NOT EXISTS items TEXT;

-- Estados validos (se recrea el CHECK para sumar CANCELADO en bases viejas)
ALTER TABLE vendu.giftcard_claims DROP CONSTRAINT IF EXISTS giftcard_claims_state_check;
ALTER TABLE vendu.giftcard_claims ADD CONSTRAINT giftcard_claims_state_check
    CHECK (state IN ('PENDIENTE','EMITIDO','NO_ENCONTRADO','AMBIGUO',
                     'ERROR_GIFTCARD','BLOQUEADO','CANCELADO','ENTREGADO'));

CREATE INDEX IF NOT EXISTS giftcard_claims_maq_idx
    ON vendu.giftcard_claims (maquina_id, created_at);
CREATE INDEX IF NOT EXISTS giftcard_claims_state_idx
    ON vendu.giftcard_claims (state);
CREATE INDEX IF NOT EXISTS giftcard_claims_device_idx
    ON vendu.giftcard_claims (device_id, state);
CREATE INDEX IF NOT EXISTS giftcard_claims_ip_idx
    ON vendu.giftcard_claims (ip, created_at);

-- Contadores diarios de reclamos por dispositivo / IP (dia = hora Venezuela)
CREATE TABLE IF NOT EXISTS vendu.giftcard_limits (
    scope   TEXT    NOT NULL,       -- 'dev:<device_id>' | 'ip:<ip>'
    dia     TEXT    NOT NULL,       -- YYYY-MM-DD
    count   INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (scope, dia)
);

-- Bitacora de cada gift card emitida por el bot
CREATE TABLE IF NOT EXISTS vendu.giftcard_emisiones (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id    BIGINT REFERENCES vendu.giftcard_claims(id),
    codigo      TEXT UNIQUE NOT NULL,
    monto_bs    NUMERIC(12,2),
    contexto    JSONB,
    emitida_en  timestamptz NOT NULL DEFAULT now()
);

-- ------------------------------------------------------------- permisos
GRANT USAGE ON SCHEMA vendu TO service_role, authenticated;
GRANT ALL ON vendu.giftcard_claims, vendu.giftcard_limits, vendu.giftcard_emisiones TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA vendu TO service_role;
GRANT SELECT ON vendu.giftcard_claims, vendu.giftcard_emisiones TO authenticated;

ALTER TABLE vendu.giftcard_claims    ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendu.giftcard_limits    ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendu.giftcard_emisiones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS vdz_claims_sel ON vendu.giftcard_claims;
CREATE POLICY vdz_claims_sel ON vendu.giftcard_claims
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS vdz_emisiones_sel ON vendu.giftcard_emisiones;
CREATE POLICY vdz_emisiones_sel ON vendu.giftcard_emisiones
    FOR SELECT TO authenticated USING (true);
