-- =====================================================================
--  VENDU — Reclamos "la maquina no despacho" + gift cards  ·  ARCHIVO 10
--  Prototipo: tabla `claims` para el micrositio QR (schema `vendu`).
--  Idempotente. Correr con conexion directa `postgres`.
--  NOTA: el backend sigue conectando como `postgres` (BYPASSRLS); RLS se
--  deja activado para que la app auto Realtime/authenticated pueda leer.
-- =====================================================================

CREATE TABLE IF NOT EXISTS vendu.giftcard_claims (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maquina_id  INTEGER      NOT NULL,
    mdb         TEXT         NOT NULL,
    producto    TEXT         NOT NULL,
    monto       NUMERIC(12,2),
    monto_real  NUMERIC(12,2),
    device_id   TEXT         NOT NULL,
    ip          TEXT,
    tx_key      TEXT UNIQUE,
    state       TEXT         NOT NULL DEFAULT 'PENDIENTE'
                CHECK (state IN ('PENDIENTE','EMITIDO','NO_ENCONTRADO',
                                 'AMBIGUO','ERROR_GIFTCARD','BLOQUEADO')),
    gift_code   TEXT,
    mensaje     TEXT,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz
);
CREATE INDEX IF NOT EXISTS giftcard_claims_maq_idx
    ON vendu.giftcard_claims (maquina_id, created_at);
CREATE INDEX IF NOT EXISTS giftcard_claims_state_idx
    ON vendu.giftcard_claims (state);

GRANT USAGE ON SCHEMA vendu TO service_role;
GRANT ALL ON vendu.giftcard_claims TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA vendu TO service_role;
GRANT SELECT ON vendu.giftcard_claims TO authenticated;
CREATE POLICY vdz_claims_sel ON vendu.giftcard_claims
    FOR SELECT TO authenticated USING (true);
ALTER TABLE vendu.giftcard_claims ENABLE ROW LEVEL SECURITY;

-- El bot (backend) genera el codigo de gift card; tabla de referencia:
CREATE TABLE IF NOT EXISTS vendu.giftcard_emisiones (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id    BIGINT REFERENCES vendu.giftcard_claims(id),
    codigo      TEXT UNIQUE NOT NULL,
    monto_bs    NUMERIC(12,2),
    contexto    JSONB,
    emitida_en  timestamptz NOT NULL DEFAULT now()
);
GRANT ALL ON vendu.giftcard_emisiones TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA vendu TO service_role;
ALTER TABLE vendu.giftcard_emisiones ENABLE ROW LEVEL SECURITY;
CREATE POLICY vdz_emisiones_sel ON vendu.giftcard_emisiones
    FOR SELECT TO authenticated USING (true);